### ISSUE TITLE
My Recorded Foods

### ISSUE THREAD

**Issue by szwart** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#112]
When the "All" filter is selected under My Recorded Foods in the Food Inventory, all foods in the entire food database are listed instead of only that crewmember's recorded foods.  It should only list all foods that crewmember has ever recorded.

**Comment by coderReview** [comment]
This issue was fixed.

**Comment by szwart** [comment]
I tested this, and it's still not working for me.  When I add a few foods to consumption, then go to the Food Inventory and sort by "All", it gives me a note "I'm sorry, but there are no foods that match your filter criteria".  I get the same message if I search by "This week" or "This Month".

**Comment by szwart** [comment]
Sorry – I think I wasn’t being clear enough.  We like that it will capture ad hoc items, but we would also like it to capture any other foods that user has logged that week, month, or over the course of the mission.

**Comment by rsial2** [comment]
Hi @coderReview do you have an update on this?

**Comment by coderReview** [comment]
@rsial2 Sorry for the delay. By noon tomorrow I will have this issue fixed. Thanks.

**Comment by coderReview** [comment]
Fixed. 
@szwart When you try this fix, please remove previous version of the iPad application.

**Comment by rsial2** [comment]
Hey @szwart, a new build is ready with this fix. Please delete the old version and reinstall using the new version. Same download link as before :)
