### ISSUE TITLE
Barcode Scanning

### ISSUE THREAD

**Issue by szwart** [NASA-Tournament-Lab/NTL-ISS-Food-Intake-Tracker#179]
1. Barcode scan something that is in the database.
2. Click Add to Consumption, then click Scan another barcode.
3. Scan something not in database.
4. Message pops up indicating that no product for that barcode is found.  Click ok.
5. The only way for the user to get back to the consumption page is to tap Profile or Help/Settings and then tap Consumption.

**Comment by rsial2** [comment]
@coderReview please fix.

**Comment by coderReview** [comment]
@rsial2 looking at this.

**Comment by nithyaasworld** [comment]
@coderReview I am not able to reproduce. I see a cancel button to get back. Are you able to reproduce?

![image](https://cloud.githubusercontent.com/assets/5114190/23245224/f923343a-f9b0-11e6-9c6a-b8cae25b24a7.png)

**Comment by nithyaasworld** [comment]
I am able to reproduce.

**Comment by coderReview** [comment]
What did you do different?

**Comment by nithyaasworld** [comment]
Just followed the exact steps in the Issue description.

**Comment by coderReview** [comment]
fixed. new version in HockeyApp.
cc @szwart, @rsial2 and @nithyaasworld

**Comment by nithyaasworld** [comment]
App crashes on adding the food via scan barcode for the first time.

I think it is not because of this fix. So I have raised a separate issue (#181) for that.

**Comment by coderReview** [comment]
No need. Fixed already. My bad

**Comment by nithyaasworld** [comment]
Thanks. Is it available via Hockeyapp?

**Comment by coderReview** [comment]
Available now

**Comment by nithyaasworld** [comment]
Verified.

**Comment by rsial2** [comment]
Hi @szwart, this has been fixed. Can you download the latest and verify?

**Comment by szwart** [comment]
I’m still having an issue, but it is slightly different now.  When I log in to a user and barcode scan an item, I get an error message “Error. OK”.  If I click OK, then scan that same item again, it captures the item just fine.  It only seems to do it the first time I barcode scan an item with a particular user.  I tried it using Saint-Jacques’ profile and then repeated the issue with Vande_Hei’s profile.

**Comment by rsial2** [comment]
@coderReview please fix.

**Comment by coderReview** [comment]
@szwart I can't reproduce the issue. I've uploaded a new version to hockeyapp just for testing this. Please use this new version.

**Comment by coderReview** [comment]
@szwart Can you let me know when you start the test? I want to track the logs.

**Comment by szwart** [comment]
Will do.  Thanks.

**Comment by szwart** [comment]
I’m starting it now.

**Comment by coderReview** [comment]
@szwart Great. If you manage to reproduce the issue let me know.

**Comment by szwart** [comment]
I can’t seem to reproduce that issue now…

**Comment by rsial2** [comment]
Thanks @szwart, closing this issue.
